### ISSUE TITLE
请问有对比实时流式处理的效果吗

### ISSUE THREAD

**Issue by AaZz101** [yuguochencuc/DB-AIAT#4]
我大致看了下论文，发现其中用到了LN,GN,以及BiGRU，据我所知，这些应该都没法直接转成实时流式处理，请问你们有做过或者考虑过流式处理吗，另外问下多头注意力机制可以流式处理吗

**Comment by yuguochencuc** [comment]
您好，为了在voicebank数据集下与目前sota模型做比较（大部分sota目前在这个数据集下都是非因果非实时设置），我们使用的都是非因果的设置，也就是说不是real-time的。因此，我们使用了bi-gru，正常的self-attention和pooling等操作。事实上，我们同样将我们的模型改成因果设置，也就是实时系统，和别的模型在dns challenge以及wsj数据集下进行了比较。其中，把gru变成单向，讲多头注意力机制改成masked self-attention即可。关于多头注意力机制如何进行流式处理，你可以参考下面这篇文章。
Nicolson, Aaron, and Kuldip K. Paliwal. "Masked multi-head self-attention for causal speech enhancement." Speech Communication 125 (2020): 80-96

**Comment by AaZz101** [comment]
谢谢你的解答，注意力机制这个对我很有用，另外LN和GN也需要修改吧，如果一帧一帧输入的话这个应该就用不了了

**Comment by yuguochencuc** [comment]
Normalization其实是没关系的 因为训练的时候是非因果的没关系，但是推理的时候保证是因果的就好啦。训练的时候Norm在学习，推理的时候Norm的值都是固定的，训练所以应该不影响结果。这部分可能我有一部分理解错误，但是目前据说我所了解几种Norm方式应该都不影响实时性的。发自我的iPhone------------------ 原始邮件 ------------------发件人: zhuoy  ***@***.***>发送时间: 2022年2月3日 12:00收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 请问有对比实时流式处理的效果吗 (Issue #4)
谢谢你的解答，注意力机制这个对我很有用，另外LN和GN也需要修改吧，如果一帧一帧输入的话这个应该就用不了了

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1028579265",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1028579265",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AaZz101** [comment]
据我所知，像BN 和IN 在pytorch中 是有trace_running_state这个选项的，开启这个选项 可以将训练数据集的数值保存 然后在eval阶段是可以使用固定值的，但是对于IN这样做效果没有单独对一段语音做IN效果好，对于LN的话没有trace_running_state这个选项，所以无法流式处理，因为其涉及到了T这个维度。针对这一点倒是在Convtasnet中有cumLN这种做法，但是效果也是下降挺多的。当然这个是我的理解，因为我看很多论文中用到了LN等，所以产生了疑虑。

**Comment by yuguochencuc** [comment]
感谢您的解答，这部分其实之前我们一直用的是BN和IN，由于我们也没有实时测过这部分的延时，所以可能也存在了一定的理解错误。这部分我会去再好好研究一下各种normalization对于实时性的影响。确实也没有怎么看到过相关文章对这部分有比较多的介绍，希望之后能再交流一下这个问题。发自我的iPhone------------------ 原始邮件 ------------------发件人: zhuoy  ***@***.***>发送时间: 2022年2月3日 22:40收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 请问有对比实时流式处理的效果吗 (Issue #4)
据我所知，像BN 和IN 在pytorch中 是有trace_running_state这个选项的，开启这个选项 可以将训练数据集的数值保存 然后在eval阶段是可以使用固定值的，但是对于IN这样做效果没有单独对一段语音做IN效果好，对于LN的话没有trace_running_state这个选项，所以无法流式处理，因为其涉及到了T这个维度。针对这一点倒是在Convtasnet中有cumLN这种做法，但是效果也是下降挺多的。当然这个是我的理解，因为我看很多论文中用到了LN等，所以产生了疑虑。

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1029056434",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1029056434",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AaZz101** [comment]
嗯嗯 BN 和IN如果用的是训练过程中的值的话，确实在eval 过程中就可以直接使用，也不会产生延时，我的意思是 如果进行流式处理，一次只能输入一帧 那么像IN和LN这种标准定义中涉及到T帧及其对应的F和C一起做normlization的应该就没法用，没办法与训练对应上。

**Comment by AaZz101** [comment]
现在能做到流式处理，据我所知有像BN ,IN 使用trace_running_state选项，还有cumLN，以及DTLN中的InstantNorm，就是在F和C这两个维度上做normalization，因为我是做音视频会议算法的，需要落地到硬件里，所以会对能否流式处理很关注。

**Comment by yuguochencuc** [comment]
了解了，但是我们做Normalization的时候，其实都是的训练时候用整个做IN LN这种，然后测试的时候都是固定好训练时候的值，然后不会变化。所以这样其实在T纬度做了也不影响的，因为测试的时候值都是固定的。但是您说的这几种只在F和C纬度做的话 肯定能保证一直是流式处理，肯定能满足实时要求的。我会再去看看您说的这几个，谢谢发自我的iPhone------------------ 原始邮件 ------------------发件人: zhuoy  ***@***.***>发送时间: 2022年2月4日 01:28收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 请问有对比实时流式处理的效果吗 (Issue #4)
现在能做到流式处理，据我所知有像BN ,IN 使用trace_running_state选项，还有cumLN，以及DTLN中的InstantNorm，就是在F和C这两个维度上做normalization，因为我是做音视频会议算法的，需要落地到硬件里，所以会对能否流式处理很关注。

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1029226745",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1029226745",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AaZz101** [comment]
嗯嗯，我的意思也是这样，就是说这种处理对于IN来说应该是没有对单条数据做IN效果好的，所以我就是想问问你们有没有做过把IN，LN换成BN之后的效果对比，因为BN使用起来还是比较方便的

**Comment by yuguochencuc** [comment]
之前有在别的模型试过这几种normalization，当时是IN效果最好。可以把我这个模型里的LN都换成BN试试，我最近有时间测试一下吧。谢谢啦发自我的iPhone------------------ 原始邮件 ------------------发件人: zhuoy  ***@***.***>发送时间: 2022年2月4日 01:39收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 请问有对比实时流式处理的效果吗 (Issue #4)
嗯嗯，我的意思也是这样，就是说这种处理对于IN来说应该是没有对单条数据做IN效果好的，所以我就是想问问你们有没有做过把IN，LN换成BN之后的效果对比，因为BN使用起来还是比较方便的

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1029236290",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1029236290",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AaZz101** [comment]
好的 ，测试过的话，希望结果能告知我一下

**Comment by AaZz101** [comment]
我测试过，对于同一条语音的不同幅度，比如归一化之后的0.1 和0.8，使用IN 这样在T和F维度训练出来的往往对幅度较低的小语音也会有很好的效果，而BN这样就不行，这也是落地需要考虑的一个点，目前也是很头疼

**Comment by yuguochencuc** [comment]
是的，落地的话好像Instance Normalization和BN的 延时还不一样，我们还有一种能量归一化的预处理，也是在整个时域波形做，也会有一定性能提升，落地的话这些确实都需要改动的。幅值的数值影响对于整个网络还是很大的，推荐您看一下我们之前的关于压缩谱的工作，文章中也有引用，这部分对于幅度谱的压缩可以显著提升性能。关于各种Norm对于实时性处理的影响，我会近期去做一下实验试试的。发自我的iPhone------------------ 原始邮件 ------------------发件人: zhuoy  ***@***.***>发送时间: 2022年2月4日 11:53收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 请问有对比实时流式处理的效果吗 (Issue #4)
我测试过，对于同一条语音的不同幅度，比如归一化之后的0.1 和0.8，使用IN 这样在T和F维度训练出来的往往对幅度较低的小语音也会有很好的效果，而BN这样就不行，这也是落地需要考虑的一个点，目前也是很头疼

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1029611515",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1029611515",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AaZz101** [comment]
好的，谢谢，我去看一下

**Comment by yuguochencuc** [comment]
hi您好，我们去仔细研究了一下各种Norm的方式，发现确实只有BN可以简单的真正做到流式处理，IN那个trace_running_state设置之后效果会不太理想。LN和GN都不能做到流式处理。我同学也在做一个Cum的Norm，准备看看结果，只有有进展告诉您一声。请问您之前试过的cum Norm效果怎么样啊 是哪篇文章里的发自我的iPhone------------------ 原始邮件 ------------------发件人: zhuoy  ***@***.***>发送时间: 2022年2月4日 01:28收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 请问有对比实时流式处理的效果吗 (Issue #4)
现在能做到流式处理，据我所知有像BN ,IN 使用trace_running_state选项，还有cumLN，以及DTLN中的InstantNorm，就是在F和C这两个维度上做normalization，因为我是做音视频会议算法的，需要落地到硬件里，所以会对能否流式处理很关注。

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1029226745",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1029226745",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AaZz101** [comment]
这篇文章里 有做了实验。效果也是下降了的。 Conv-TasNet: Surpassing Ideal Time-Frequency Magnitude Masking for Speech Separation
https://github.com/JusperLee/Conv-TasNet

**Comment by yuguochencuc** [comment]
好的好的感谢啦 这部分我之前还没有仔细看 现在好好研究一下实际落地这块的一些问题 发自我的iPhone------------------ 原始邮件 ------------------发件人: zhuoy  ***@***.***>发送时间: 2022年2月12日 00:11收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 请问有对比实时流式处理的效果吗 (Issue #4)
这篇文章里 有做了实验。效果也是下降了的。 Conv-TasNet: Surpassing Ideal Time-Frequency Magnitude Masking for Speech Separation
https://github.com/JusperLee/Conv-TasNet

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1036372856",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/4#issuecomment-1036372856",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
