### ISSUE TITLE
关于您的论文

### ISSUE THREAD

**Issue by AIHHU** [yuguochencuc/DB-AIAT#6]
在论文中，我看到您把音频降采样到了16khz，在这个代码中有提现吗？还有就是想问一下，如果我的输入是个16khz数据，还能增强吗

**Comment by yuguochencuc** [comment]
我整个网络针对的就是16K的数据哦，只是训练的时候把训练音频从48k下采样到16k，在我放出的代码中是没有体现的。你要用的话，直接输入16k音频就好

**Comment by AIHHU** [comment]
就是训练的时候降采样到16k吗？还是说训练时候还是用您那个48khz数据，然后我进行推理部署的时候可以用16khz?

**Comment by AIHHU** [comment]
就是我有点不太明白，您代码里对训练的原始48khz数据有没有进行降采样，这个我没有看出来，enhance的时候是可以用16khz的吧

**Comment by AIHHU** [comment]
我现在就是不知道我下下来那个您文章中48khz的原始数据，有没有必要先自己降采样到16khz，然后再用您的代码训练

**Comment by yuguochencuc** [comment]
你好，VB数据集是有已经降采样过的数据集。当然你也可以自己把48K降到16K，我的模型是针对16K的，目前针对全带的文章还比较少发自我的iPhone------------------ 原始邮件 ------------------发件人: hhu小菜鸡  ***@***.***>发送时间: 2022年3月17日 11:54收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 关于您的论文 (Issue #6)
我现在就是不知道我下下来那个您文章中48khz的原始数据，有没有必要先自己降采样到16khz，然后再用您的代码训练

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1070274644",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1070274644",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yuguochencuc** [comment]
我的模型训练和推理都是针对16K的数据，你如果有48K的数据要进行训练或者推理，都需要先自己下采样到16K，然后你也可以自己在代码里用Librosa下采样一边发自我的iPhone------------------ 原始邮件 ------------------发件人: hhu小菜鸡  ***@***.***>发送时间: 2022年3月17日 11:52收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 关于您的论文 (Issue #6)
就是我有点不太明白，您代码里对训练的原始48khz数据有没有进行降采样，这个我没有看出来，enhance的时候是可以用16khz的吧

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1070272075",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1070272075",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AIHHU** [comment]
谢谢学长！但是我根据宁那篇论文去找的VB数据集，那个我只找到了48khz的，没有找到16khz的，请问宁是直接下载的16khz的数据集吗？能否提供一下网址呢？

**Comment by yuguochencuc** [comment]
如果没问题的话应该是这个数据集，你去看看吧。在很多论文里也有引用的。https://datashare.ed.ac.uk/handle/10283/1942

**Comment by AIHHU** [comment]
学长欧，这个就是48khz咩，那我在宁代码里的sf.read这里添加一个sample_rate=16k是不是就行了

**Comment by yuguochencuc** [comment]
我发给你的这个应该是16k的啊 你下载看了吗？这个数据集16k和48k的都有，你这么做不太对哦，要先用下采样。

**Comment by yuguochencuc** [comment]
他名字写的是48k 但是实际是16k的数据，你下载下来就知道了

**Comment by AIHHU** [comment]
!这样的吗，我read一下看看

**Comment by AIHHU** [comment]
学长，我发现了，这个还数据集挺好玩，训练的确是16k的，但是测试集竟然是48k

**Comment by AIHHU** [comment]
学长欧，请问您最后是用了多卡训练吗，我发现显存32G有点不太够用咩

**Comment by yuguochencuc** [comment]
是会非常占显存 你可以把Batchsize调低一点或者是把语音截短一点再试试发自我的iPhone------------------ 原始邮件 ------------------发件人: hhu小菜鸡  ***@***.***>发送时间: 2022年3月18日 15:31收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 关于您的论文 (Issue #6)
学长欧，请问您最后是用了多卡训练吗，我发现显存32G有点不太够用咩

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1072100964",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1072100964",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AIHHU** [comment]
但是推理时候应该不会太占内存吧？

**Comment by yuguochencuc** [comment]
推理的时候 Rtf也相对比较高，就是会慢一点而已，你可以试试 我放了训练好的模型进去的，但是语音也不能一次不能太长了 也会比较占显寸发自我的iPhone------------------ 原始邮件 ------------------发件人: hhu小菜鸡  ***@***.***>发送时间: 2022年3月18日 22:53收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 关于您的论文 (Issue #6)
但是推理时候应该不会太占内存吧？

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1072487531",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1072487531",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AIHHU** [comment]
学长，请问您是用什么平台训练的呢？华为云太贵了，受不了了

**Comment by yuguochencuc** [comment]
用的自己实验室的服务器发自我的iPhone------------------ 原始邮件 ------------------发件人: hhu小菜鸡  ***@***.***>发送时间: 2022年3月19日 02:27收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, Comment ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 关于您的论文 (Issue #6)
学长，请问您是用什么平台训练的呢？华为云太贵了，受不了了

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1072680291",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1072680291",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AIHHU** [comment]
学长，请问您这个大概跑到多少个epoch呢？我这里拿着宁的best_model进行fine-tune，4个epoch下来pesq只有2.5,请问您跑了多少epoch呢？

**Comment by yuguochencuc** [comment]
你直接拿拿Bestmodel推理一下试试吧 我觉得你拿Best model finetune这个结果肯定不太对发自我的iPhone------------------ 原始邮件 ------------------发件人: hhu小菜鸡  ***@***.***>发送时间: 2022年3月19日 20:11收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, State change ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 关于您的论文 (Issue #6)
学长，请问您这个大概跑到多少个epoch呢？我这里拿着宁的best_model进行fine-tune，4个epoch下来pesq只有2.5,请问您跑了多少epoch呢？

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1072999157",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1072999157",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AIHHU** [comment]
好，主要是我们数据集不太一样，我跑的更多是denoise，就是降低噪声，背景音是场景噪声，不是人声，还有就是predict这个文件是做什么的呢？

**Comment by yuguochencuc** [comment]
你直接拿Best Model推理应该就是3.3左右吧 不知道你是怎么训练的，我大概40轮就收敛了发自我的iPhone------------------ 原始邮件 ------------------发件人: hhu小菜鸡  ***@***.***>发送时间: 2022年3月19日 20:11收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Guochen Yu ***@***.***>, State change ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 关于您的论文 (Issue #6)
学长，请问您这个大概跑到多少个epoch呢？我这里拿着宁的best_model进行fine-tune，4个epoch下来pesq只有2.5,请问您跑了多少epoch呢？

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1072999157",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/6#issuecomment-1072999157",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
