### ISSUE TITLE
关于性能问题

### ISSUE THREAD

**Issue by AIHHU** [yuguochencuc/DB-AIAT#7]
学长，宁的代码我在8khz和16khz下都跑过了，8kh我调了相关参数，效果上的确能达到您论文里的，但是16khz不管是微调还是从头开始训练，效果上pesq一直在2.3,请问这是为什么呢？

**Comment by AIHHU** [comment]
学长，我怀疑宁最后进行评估的pesq并不是用的wb模式，应该用的nb模式，代码里有点问题

**Comment by yuguochencuc** [comment]
Nb的话指标是更高的，但是我自己测的时候是用的WB测的哦 所有Vb上的BASELINE都是WB测的，我上传的代码里验证的时候的Pesqloss也是用的WB的，代码里有体现的。并且你可以直接用我训练好的Checkpoint自己Inference然后测一下，是没有问题的，你可以好好看看。还有我不明白你说的8KHz 16KHz都是用的Vb数据集吗？是你自己做了重采样吗？我没理解你的问题。发自我的iPhone------------------ 原始邮件 ------------------发件人: hhu小菜鸡  ***@***.***>发送时间: 2022年3月27日 13:46收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 关于性能问题 (Issue #7)
学长，我怀疑宁最后进行评估的pesq并不是用的wb模式，应该用的nb模式，代码里有点问题

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/7#issuecomment-1079845442",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/7#issuecomment-1079845442",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yuguochencuc** [comment]
首先模型在8K和16K采样率的数据下，网络结构本来就应该要调整的，因为Frequency bins都不一样了，F维都不一样，直接用一个网络训练肯定有问题，所以你如果要重采样用不同的采样率的数据训练，最好先把网络结构作一定调整发自我的iPhone------------------ 原始邮件 ------------------发件人: hhu小菜鸡  ***@***.***>发送时间: 2022年3月27日 13:46收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 关于性能问题 (Issue #7)
学长，我怀疑宁最后进行评估的pesq并不是用的wb模式，应该用的nb模式，代码里有点问题

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/7#issuecomment-1079845442",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/7#issuecomment-1079845442",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AIHHU** [comment]
对，我是调过的，就是您论文里我怀疑是用nb测得，并不是wb，是吗？

**Comment by yuguochencuc** [comment]
貌似我说的已经很清楚了，我都是用wb-pesq测的，代码里的测试时候的pesq_loss也已经提供。并且在vb数据集上大家都是用的wb测的，没有人用nb pesq测。我在best_model里面放了训练好的模型，你可以直接拿来在vb上面测wb pesq。还有就是你说的pesq的数值问题，我都不知道你是在哪个数据集上跑的，这个数值好像也没用可比性吧。至于8k和16k数据的问题，我的模型在16k的vb数据集和dns challenge数据集上都跑了，在16k数据集结果都很正常，效果也没有任何问题，我不知道你的问题出在哪儿哦。如果你要用不同采样率的数据训练，最好先把模型好好修改好，和别的baseline比较一下。






发件人："hhu小菜鸡" ***@***.***>
发送日期：2022-03-29 13:16:36
收件人：yuguochencuc/DB-AIAT ***@***.***>
抄送人：Guochen Yu ***@***.***>,State change ***@***.***>
主题：Re: [yuguochencuc/DB-AIAT] 关于性能问题 (Issue #7)

对，我是调过的，就是您论文里我怀疑是用nb测得，并不是wb，是吗？

**Comment by yuguochencuc** [comment]
你指的8KHz 16KHz是什么？是采样率还是频带宽呢 还有就是你用的是什么数据集呢 我没懂你在16KHz Pesq2.3是在哪个数据集？我在Vb测试集上 16采样率 使用WB-Pesq测出来的是3.30发自我的iPhone------------------ 原始邮件 ------------------发件人: hhu小菜鸡  ***@***.***>发送时间: 2022年3月27日 11:11收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] 关于性能问题 (Issue #7)
学长，宁的代码我在8khz和16khz下都跑过了，8kh我调了相关参数，效果上的确能达到您论文里的，但是16khz不管是微调还是从头开始训练，效果上pesq一直在2.3,请问这是为什么呢？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/7",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/7",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AIHHU** [comment]
我懂了，这样听下来的话应该是数据集的问题，我用的wham!数据集跑的，可能的确效果会不太一样，因为vb数据集他是以人声作为噪声的，而wham!完全是用背景声作为噪声，其实我听了一下，尽管wb模式下在wham!数据集上pesq只有2.4，但是效果还是非常不错的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Guochen ***@***.***>
发送时间: 2022年3月29日 15:10
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [yuguochencuc/DB-AIAT] 关于性能问题 (Issue #7)

貌似我说的已经很清楚了，我都是用wb-pesq测的，代码里的测试时候的pesq_loss也已经提供。并且在vb数据集上大家都是用的wb测的，没有人用nb pesq测。我在best_model里面放了训练好的模型，你可以直接拿来在vb上面测wb pesq。还有就是你说的pesq的数值问题，我都不知道你是在哪个数据集上跑的，这个数值好像也没用可比性吧。至于8k和16k数据的问题，我的模型在16k的vb数据集和dns challenge数据集上都跑了，在16k数据集结果都很正常，效果也没有任何问题，我不知道你的问题出在哪儿哦。如果你要用不同采样率的数据训练，最好先把模型好好修改好，和别的baseline比较一下。






发件人："hhu小菜鸡" ***@***.***>
发送日期：2022-03-29 13:16:36
收件人：yuguochencuc/DB-AIAT ***@***.***>
抄送人：Guochen Yu ***@***.***>,State change ***@***.***>
主题：Re: [yuguochencuc/DB-AIAT] 关于性能问题 (Issue #7)

对，我是调过的，就是您论文里我怀疑是用nb测得，并不是wb，是吗？
―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>






―
