### ISSUE TITLE
dual_aia_complex_trans和dual_aia_trans_merge_crm有什么区别吗？

### ISSUE THREAD

**Issue by AIHHU** [yuguochencuc/DB-AIAT#8]
学长好~请问dual_aia_complex_trans和dual_aia_trans_merge_crm有没有什么区别？难道说前者推理速度更快一点？

**Comment by yuguochencuc** [comment]
你好 前者在最后将两分支结合的时候和后者有区别 你可以看一下代码，里面有体现。后者效果会更好一些发自我的iPhone------------------ 原始邮件 ------------------发件人: hhu小菜鸡  ***@***.***>发送时间: 2022年4月16日 19:04收件人: yuguochencuc/DB-AIAT ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [yuguochencuc/DB-AIAT] dual_aia_complex_trans和dual_aia_trans_merge_crm有什么区别吗？ (Issue #8)
学长好~请问dual_aia_complex_trans和dual_aia_trans_merge_crm有没有什么区别？难道说前者推理速度更快一点？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yuguochencuc/DB-AIAT/issues/8",
"url": "https://github.com/yuguochencuc/DB-AIAT/issues/8",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
